### ISSUE TITLE
0.6.1 docker hub release

### ISSUE THREAD

**Issue by avindra** [jwilder/dockerize#116]
https://hub.docker.com/r/jwilder/dockerize/tags/

Seems the docker hub image hasn't been updated, any plans on pushing?

**Comment by timb07** [comment]
I've just been caught out by #107 when using the docker hub image, not realising it wasn't up to date.

In addition, when trying to see what version was in the docker image, I discovered this:

```
5b6645b374bd:/# /usr/local/bin/dockerize -version

5b6645b374bd:/#
```

That is, it's not outputting a version number, so I had to do extra digging to work out that it was in fact an old version.

**Comment by powerman** [comment]
Up-to-date version is available in fork https://github.com/powerman/dockerize and also there is docker image https://hub.docker.com/r/powerman/dockerize/:
```sh
$ docker run -i -t --rm powerman/dockerize -version
dockerize v0.9.2 go1.11.2
```

**Comment by avindra** [comment]
Sounds good. Thanks @powerman I'll keep the issue open for visibility

**Comment by jwilder** [comment]
Pushed.
