### ISSUE TITLE
'-wait' check timeout

### ISSUE THREAD

**Issue by xingguang2013** [jwilder/dockerize#124]
Container A uses the --link parameter to connect to container B at startup, and uses the -wait parameter in the A container's Dockerfile to check the TCP service connection with container B. After container A started, it can connect to container B after using ping command. But the container A service starts checking the container B's tcp service timeout

**Comment by powerman** [comment]
I'm not sure I understand your English. Can you please try latest version from fork https://github.com/powerman/dockerize and open new issue there if you still have this issue?
