### ISSUE TITLE
"no command specified" on every command

### ISSUE THREAD

**Issue by oryband** [jwilder/dockerize#13]
running this inside an ubuntu latest image:
```bash
$ dockerize -template x:y
2015/10/22 07:13:12 no command specified
$ dockerize -stderr x
2015/10/22 07:13:50 no command specified
# this goes on for everything i do, except -version which does seem to work
```

any idea what is wrong? the output is really unhelpful

**Comment by oryband** [comment]
@doodyparizada

**Comment by oryband** [comment]
i understand now that i was missing the app to be executed after the template finished processing.
the help line is a little misleading:
```
$ dockerize -h
Usage of dockerize:
  -delims string
        template tag delimiters. default "{{":"}}"
  -stderr value
        Tails a file to stderr. Can be passed multiple times
  -stdout value
        Tails a file to stdout. Can be passed multiple times
  -template value
        Template (/template:/dest). Can be passed multiple times
  -version
        show version
```
- i'm missing an "how to execute" line at the top of the help file
- also, i'd like to have a way to just generate a template without executing anything

**Comment by oryband** [comment]
right now i'm bypassing this by passing `true` to the app part:
```bash
$ docker -template x:y true && my_app
```
but this is a hack

it feels like dockerize is trying to achieve two things at once instead of going the unix way and splitting the features into two separate tools which can be bundled together if necessary. wdyt?

**Comment by jwilder** [comment]
@oryband I think some kind of a `-dry-run` feature would be useful.  Good idea.

**Comment by jwilder** [comment]
The `no command specified` could be improved as well.

**Comment by doodyparizada** [comment]
I know it's not backward compatible, but I would prefer that `dockerize`'s default behaviour would be to not expect a command be given (i.e. default `-dry-run`) so it just renders the template. If you want to give a command, you would have to specify `--command="XXX XXX"`

**Comment by jwilder** [comment]
@oryband I've updated the usage as well as made command optional as well.

@doodyparizada Command is not optional.  You can render templates to standard output for debugging by leaving off the `:/dest` portion.

**Comment by oryband** [comment]
@jwilder thanks!

however, I think adding an example of the hack I did above is a good idea (providing `true` as a command). Some people (like myself) would only like to use the templating feature of dockerize, without the execution part. If we're keeping the command as required, we should at least provide an example how to bypass it.

**Comment by md5** [comment]
@oryband It sounds like you may be better off using [`jwilder/docker-gen`](https://github.com/jwilder/docker-gen) instead of `dockerize`.

**Comment by oryband** [comment]
@md5 I did at first, but it requires mounting the docker socket file in order to fetch environment variables. This is kinda overkill for the purpose of templating.

There is no other golang cli template tool available beside these two tools.

**Comment by md5** [comment]
@md5 You're right. That was a silly suggestion on my part.

**Comment by oryband** [comment]
why are you talking to yourself? :)

**Comment by md5** [comment]
Why not achieve maximum silliness?
