### ISSUE TITLE
ARM / arm64 support?

### ISSUE THREAD

**Issue by haakonstorm** [jwilder/dockerize#154]
Hey all! Great project. Any plans or possibilities for arm64 support, e.g. for running on ODROID-N2 SBCs or the Pi 4?

**Comment by kaissi** [comment]
When we talk about **armv8** architecture (the latest 64-bit ARM-powered devices - also known as **aarch64**), we are talking about [arm64](https://wiki.debian.org/Arm64Port) (the Debian port name).

This request was made here in #143. I also made a Pull Request fixing that (#155)
