### ISSUE TITLE
Download not working for Apline Linux amd64

### ISSUE THREAD

**Issue by jlenos-inflight** [jwilder/dockerize#166]
Looks like the download link for the latest release 0.6.1 is not working. Seems to have just broken as I have builds in my CI that worked using the link a few hours ago.

https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-alpine-linux-amd64-v0.6.1.tar.gz

**Comment by adar2378** [comment]
Same here

**Comment by annabkr** [comment]
Us, too.

**Comment by arvinwiyono** [comment]
Same here...

**Comment by desaiuditd** [comment]
Same. Just like @jlenos-inflight it's affecting our CI pipeline. We temporarily switched to `v0.6.0` to unblock ourselves.

**Comment by desaiuditd** [comment]
Seems like a broader Github or AWS issue. It's also affecting other Github projects as well. E.g., https://github.com/wp-cli/wp-cli/releases/tag/v2.4.0

**Comment by jlenos-inflight** [comment]
Looks like the download is functional again 😄. We will be moving to include the binary in our images to mitigate this from happening again. Thanks!
