### ISSUE TITLE
dockerhub tag for 0.7?

### ISSUE THREAD

**Issue by tooptoop4** [jwilder/dockerize#196]
can't find the new release on dockerhub cc @jwilder

**Comment by markuspeloquin** [comment]
It's probably because https://github.com/jwilder/dockerize/commit/11dc70058198aa6772afc1155a731c148f0a9b2a was created *after* the v0.7.0 tag and the tag was never updated. `go install github.com/jwilder/dockerize@latest` hasn't worked in two months.

**Comment by tooptoop4** [comment]
🦗

**Comment by tooptoop4** [comment]
👋 @jwilder

**Comment by tp-jssk** [comment]
@jwilder Any update on this?

**Comment by tooptoop4** [comment]
dis abandonware 💀
