### ISSUE TITLE
`go install github.com/jwilder/dockerize@v0.9.0` fails due to `replace` directive in `go.mod`

### ISSUE THREAD

**Issue by BusterNeece** [jwilder/dockerize#217]
Hello!

Our project depends on a number of Golang dependencies, so to optimize our build process we run multiple `go install` commands consecutively in one build stage and then copy the resulting binaries.

Following the release of 0.9.0, this is no longer possible due to how this project is configured:

```
$ go install github.com/jwilder/dockerize@v0.9.0
go: downloading github.com/jwilder/dockerize v0.9.0
go: github.com/jwilder/dockerize@v0.9.0 (in github.com/jwilder/dockerize@v0.9.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Is this something solvable from our end? I'd love to be able to continue using our existing workflow if possible.

**Comment by jwilder** [comment]
`go install github.com/jwilder/dockerize@v0.9.1` should fix this.

Fixed by #219
