### ISSUE TITLE
-wait for UDP

### ISSUE THREAD

**Issue by metmajer** [jwilder/dockerize#25]
Is there a particular reason why UDP is not supported together with `-wait`? I am not proficient with Go, but it appears to me, that [`net.DialTimeout` and callees](https://golang.org/src/net/dial.go?s=5630:5708#L181) do support it.

Could provide a PR unless you have any objections with extending [func waitForDependencies()](https://github.com/jwilder/dockerize/blob/master/dockerize.go#L82) with `udp`, `udp4` and `udp6`. Thanks!

**Comment by jwilder** [comment]
I don't see any reason why it could not support `udp` as well. PR would be great.

**Comment by metmajer** [comment]
Resolved with PR #26.
