### ISSUE TITLE
Http waiting - specify specific URL?

### ISSUE THREAD

**Issue by bobbotron** [jwilder/dockerize#35]
I was wondering if it's possible to specify a full URL when waiting for http/https resources to come online.  Our application server will return 200's on /, but I'd like to poll some resource like /sub/resource, which will return something like 404 until the application is totally loaded.  Is it possible to do this with dockerize?  Like:

`dockerize -wait http://web:80/sub/resource`

**Comment by jwilder** [comment]
Yes.  See: https://github.com/jwilder/dockerize#waiting-for-other-dependencies
