### ISSUE TITLE
Allow -wait value to be templated

### ISSUE THREAD

**Issue by ColinHebert** [jwilder/dockerize#38]
It would be useful to be able to use go templates when specifying the host we want to wait for. Especially since the hostname/port could be provided by the environment.

here's an example of what it would look like for a user of dockerize

``` dockerfile
FROM alpine

ADD output/dockerize /bin/dockerize
ENTRYPOINT ["dockerize", "-wait", "{{ .Env.SERVICE_ADDR }}"]
CMD ["myscript.sh"]
```

**Comment by driverpt** [comment]
Doesn't that work with Env Variables?

**Comment by jwilder** [comment]
I believe you can already do this w/ env vars as @driverpt pointed out:

```
FROM dockerize
CMD dockerize -wait $HOST echo "foo"
```

`docker run -e HOST=http://localhost -it foo`

**Comment by mkarpusiewicz** [comment]
It does not work on scratch images when you run without a shell to expand environment variables. The proposed solution to use templates in -wait command would be a very nice addition (something like https://github.com/markriggins/dockerfy does)
