### ISSUE TITLE
Dockerize and sub process exit codes

### ISSUE THREAD

**Issue by ianneub** [jwilder/dockerize#4]
Howdy,

I think dockerize fills a need that I've had over and over with docker-ized apps. Thanks!

1) Currently dockerize will never exit if the sub process exits with 0.

2) Also, if the sub process exits with anything other than 0, dockerize will exit, but it will exit with 1.

Would you accept a PR that would change the behavior to the following?

1) If the sub process exits 0, then dockerize should exit 0.

2) If the sub process exits `n`, then dockerize should exit `n` also.

**Comment by jwilder** [comment]
When it doesn't exit, are you also tailing any files?

That behavior sounds reasonable though.

**Comment by ianneub** [comment]
Yes that is correct, the tail'ing is what keeps dockerize running. Sorry I didn't mention that.

An issue I didn't consider though is cross platform portability. To get the exit status code requires a call to [Sys](http://golang.org/pkg/os/#ProcessState), which is OS specific.

My golang-fu is weak in that area. Would it be ok to make this Unix only? If not, no worries.

**Comment by ianneub** [comment]
Actually it seems that at least both Unix and Windows define the same ExitStatus function:

http://stackoverflow.com/questions/10385551/get-exit-code-go

So it will support at least those two OSes.

**Comment by jwilder** [comment]
That's fine.  dockerize only supports linux currently.
