### ISSUE TITLE
Removed line break when replacing values?

### ISSUE THREAD

**Issue by cougil** [jwilder/dockerize#46]
Hi!.
We are using your project and it appears to work correctly but we have found an issue. When we try to replace 2 environment variables when we were using a template, it appears that the replacement it actually removes one line break of the file. 
We have tested using a template like this:
`datasource.driverClassName=org.postgresql.Driver
datasource.jdbcUrl=jdbc:postgresql://{{ .Env.APP_DB_HOST }}:5432/{{ .Env.APP_DB_DATABASE }}
datasource.username=xxx`
That finally, and after replacing the values from the environment (and we have checked that they do not have any strange character) the result removed the line break between the 2nd and 3rd line, with this result:
`datasource.driverClassName=org.postgresql.Driver
datasource.jdbcUrl=jdbc:postgresql://dbhost:5432/exampledatasource.username=xxx`
Best,

**Comment by powerman** [comment]
Fork https://github.com/powerman/dockerize doesn't have this issue:
```sh
$ APP_DB_HOST=db.host APP_DB_DATABASE=db_name dockerize -template /dev/stdin <<'EOF'                                                                                          
datasource.driverClassName=org.postgresql.Driver                                                    
datasource.jdbcUrl=jdbc:postgresql://{{ .Env.APP_DB_HOST }}:5432/{{ .Env.APP_DB_DATABASE }}         
datasource.username=xxx                                                                             
EOF                               
datasource.driverClassName=org.postgresql.Driver
datasource.jdbcUrl=jdbc:postgresql://db.host:5432/db_name
datasource.username=xxx
```

**Comment by JamesJJ** [comment]
Hi @cougil  I can not reproduce the issue you mention. Here is how I tried:

```bash
echo '
datasource.driverClassName=org.postgresql.Driver
datasource.jdbcUrl=jdbc:postgresql://{{ .Env.APP_DB_HOST }}:5432/{{ .Env.APP_DB_DATABASE }}
datasource.username=xxx
' > /tmp/test-template
```
```
dockerize -version
v0.6.1
```
```
$ APP_DB_HOST='value1' APP_DB_DATABASE='value2'  dockerize  -template /tmp/test-template

datasource.driverClassName=org.postgresql.Driver
datasource.jdbcUrl=jdbc:postgresql://value1:5432/value2
datasource.username=xxx

```

Did I get the template text wrong? ... Maybe you could put the template that shows this behaviour in to [gist.github.com](https://gist.github.com) and share the link here?

**Comment by JamesJJ** [comment]
... just noticed that this issue is very old: maybe it could be closed unless still a problem?

**Comment by cougil** [comment]
I think it makes sense to close it, do not worry ;-) 
Thank you!
