### ISSUE TITLE
can this be run with alpine-node?

### ISSUE THREAD

**Issue by ksnyde** [jwilder/dockerize#47]
Alpine-node is great in its compactness but it doesn't use `libc` and has some other variations. Just wondering if this great container might be available in this flavour of Linux.

**Comment by fakraemer** [comment]
Yes it can. I assume you know this already by now, just posting this here in case someone else runs over the issue:

~~~
FROM alpine:3.4

ENV DOCKERIZE_VERSION v0.2.0
RUN apk update && \
    apk add --no-cache ca-certificates wget tar && \
    wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    apk --purge del tar && \
    rm -rf /var/cache/apk/*

ENTRYPOINT ["dockerize"]
~~~

**Comment by tkaria** [comment]
For those arriving here with problems running on alpine please note that the above works perfectly but the version as of today has been bumped to 0.3.0 so you'll need:
`ENV DOCKERIZE_VERSION v0.3.0`

**Comment by jwilder** [comment]
Yes.  There is an `alpine` build you can install: `dockerize-alpine-linux-amd64-v0.3.0.tar.gz`

https://github.com/jwilder/dockerize/releases/tag/v0.3.0
