### ISSUE TITLE
When several waits only work one

### ISSUE THREAD

**Issue by emonterodelrio** [jwilder/dockerize#51]
Hi, when launching dockerize with several waits it only waits for first service wanted.
#1

./dockerize -wait tcp://localhost:4444 -wait tcp://localhost:3333 -timeout 300s
2016/08/29 08:40:11 Waiting for host: localhost:4444
2016/08/29 08:40:11 Waiting for host: localhost:3333
2016/08/29 08:40:11 Problem with dial: dial tcp 127.0.0.1:3333: getsockopt: connection refused. Sleeping 5s
2016/08/29 08:40:11 Problem with dial: dial tcp 127.0.0.1:3333: getsockopt: connection refused. Sleeping 5s

Then launched nc -l 3333 and nc -l 4444 in several terminals.

But dockerized outputs:

2016/08/29 08:40:16 Connected to tcp://localhost:3333
2016/08/29 08:40:16 Problem with dial: dial tcp 127.0.0.1:3333: getsockopt: connection refused. Sleeping 5s
2016/08/29 08:40:21 Problem with dial: dial tcp 127.0.0.1:3333: getsockopt: connection refused. Sleeping 5s

I could make a workaround launching only one wait with each execution, like this:

./dockerize -wait tcp://localhost:3333 && ./dockerize -wait tcp://localhost:4444 -timeout 300s

**Comment by jwilder** [comment]
Not reproducible w/ `v0.3.0`
