### ISSUE TITLE
Ability to pass command line parameters into [command]

### ISSUE THREAD

**Issue by Slach** [jwilder/dockerize#71]
i need something like this:

    docker-compose run --rm myservice "dockerize -wait http://otherservice:8123 \"/bin/mycommand --param=value\""

**Comment by jwilder** [comment]
That should already be supported.  I think the quote is messing up the args.  Try:
```
docker-compose run --rm myservice dockerize -wait http://otherservice:8123 /bin/mycommand --param=value
```
