### ISSUE TITLE
Cannot chain commands with &&

### ISSUE THREAD

**Issue by chadfurman** [jwilder/dockerize#73]
I'm running postgraphql which doesn't have a nice way to send it to the background.

I want to dockerize two commands: `pg-migrator` and `postgraphql`

If I do:

```
command: dockerize -wait tcp://db:5432 pg-migrator postgres://db
command: dockerize -wait tcp://db:5432 postgraphql --watch
```

then the postgraphql command happens before the pg-migrator and the pg-migrator never runs.  If I reverse the order, then `postgraphql` runs first and `pg-migrator` never runs.  If I try and chain the commands using `pg-migrator postgres://db && postgraphql --watch` then the `pg-migrator` command gets the entire string as command-line arguments and errors out because it's expecting a version number or nothing, and ofcourse postgraphql never runs.  

Ideally, when `&&` is present, the two commands would be run in sequence.

**Comment by japsu** [comment]
`&&` is a shell feature, not that of `exec`. You are basically expecting `dockerize` to run a shell script instead of a single command.

Try `dockerize -wait tcp://db:5432 /bin/sh -c "pg-migrator postgres://db && postgraphql --watch"`.

**Comment by jwilder** [comment]
Thanks @japsu!
