### ISSUE TITLE
DNS issue when using Docker 1.13 and Compose 1.10

### ISSUE THREAD

**Issue by DonMartin76** [jwilder/dockerize#79]
Hi there,

I have an issue when waiting for other containers using `dockerize` (tested both 0.2.0 and 0.3.0): Using Docker 1.12, I could wait for a different container to become available using the service name from the compose file. In Docker 1.13/Compose 1.10 this does not seem to work anymore. `dockerize` tries to use the external DNS server for some reason, and will not resolve the internal DNS names which Compose applies to the containers.

Has anybody seen this as well? Is there a workaround?

**Comment by jwilder** [comment]
`dockerize` doesn't do anything with DNS resolution other than rely on the system configuration of it.  Sounds like something changed in docker 1.13 or compose 1.10 that caused this.  

I'd suggest opening an issue with those projects.
