### ISSUE TITLE
Ability to generate templates by glob

### ISSUE THREAD

**Issue by sstarcher** [jwilder/dockerize#8]
It would be nice to apply dockerize template to a directory and have it rename templates that end in say .tmpl

**Comment by jwilder** [comment]
This is supported via `-template /tmpl/dir:/dest/dir`.  If the src is a directory, each file is treated as a template and generated into the dest dir.

**Comment by xmlking** [comment]
@jwilder Well, this can generate translated files in a  directory,  it would be nice to rename destination files e.g., `kubernetes-realm.json.tmpl` to `kubernetes-realm.json`

I also have usecase where I have to rename the destination filename.  would be nice to provide ability to customize generated filenames also with Env params. 
     
`
CMD ["dockerize", "-template", "/opt/jboss/keycloak/realm-config/default-realm.json.tmpl:/opt/jboss/keycloak/realm-config/{{ .Env.REALM }}-realm.json", ... ]
`
