### ISSUE TITLE
http wait does not work on urls with paths - works only on the hostname

### ISSUE THREAD

**Issue by rajivgandhi1** [jwilder/dockerize#82]
dockerize -wait http://myweb:8080/some/path does not work - it seems it ignores the path and just pings the hostname on the port.

So, effectively, it only works if there is an index page setup for the web app.

The path support is needed if you want to ensure that the app started and not just initialized on the port. In my app (using spring cloud), I would prefer to wait on http://myweb:8080/health which is a sure way to know if the app has started.

**Comment by jwilder** [comment]
Not reproducible w/ `v0.3.0`.
