### ISSUE TITLE
macOS release?

### ISSUE THREAD

**Issue by mrmachine** [jwilder/dockerize#88]
Can anyone point me to a pre-built macOS binary? Or tell me how to build it myself? I tried installing `go` via Homebrew, cloning this repo and running `make` but I got this error:

```
Building dockerize
tail.go:8:2: cannot find package "github.com/hpcloud/tail" in any of:
	/usr/local/Cellar/go/1.8.3/libexec/src/github.com/hpcloud/tail (from $GOROOT)
	/Users/tailee/go/src/github.com/hpcloud/tail (from $GOPATH)
template.go:15:2: cannot find package "github.com/jwilder/gojq" in any of:
	/usr/local/Cellar/go/1.8.3/libexec/src/github.com/jwilder/gojq (from $GOROOT)
	/Users/tailee/go/src/github.com/jwilder/gojq (from $GOPATH)
exec.go:11:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/Cellar/go/1.8.3/libexec/src/golang.org/x/net/context (from $GOROOT)
	/Users/tailee/go/src/golang.org/x/net/context (from $GOPATH)
make: *** [dockerize] Error 1
```

**Comment by jwilder** [comment]
I pushed up a OS X binary here: https://github.com/jwilder/dockerize/releases/tag/v0.4.0

**Comment by mrmachine** [comment]
@jwilder Thanks for this. Any chance you could document how to build it (for future releases)? Or maybe even add a formula to Homebrew? Or I could try that, if I knew how to build it on macOS.

I ask about Homebrew because we run our projects and deploy with Docker, but we also run them locally for development natively and still make use of `dockerize` in that scenario. We install all our other dependencies when running natively via Homebrew, so having `dockerize` available on Homebrew would make it easier for our devs to get up and running without Docker.

**Comment by jwilder** [comment]
You just need go installed and you can run 'make deps' and then 'make'.

**Comment by scobiej** [comment]
Well, I have tried unsetting GOPATH, setting it to the root of the project etc. etc. with no joy. This is what I get (running in an alpine 3.7 image) ...

```83221b80b135:~/go$ git clone https://github.com/jwilder/dockerize.git
Cloning into 'dockerize'...
remote: Counting objects: 381, done.
remote: Total 381 (delta 0), reused 0 (delta 0), pack-reused 381
Receiving objects: 100% (381/381), 86.91 KiB | 556.00 KiB/s, done.
Resolving deltas: 100% (206/206), done.
83221b80b135:~/go$ cd dockerize/
83221b80b135:~/go/dockerize$ make deps
github.com/elgs/gosplitargs                        e9cf3de21e14	[OK]
github.com/hpcloud/tail                            faf842bde7ed	[OK]
github.com/jwilder/gojq                            81fa9a608a13	[OK]
golang.org/x/net                                   749a502dd1ea	[OK]
83221b80b135:~/go/dockerize$ make
Building dockerize
go install: no install location for directory /home/scobiej/go/dockerize outside GOPATH
	For more details see: 'go help gopath'
make: *** [Makefile:15: dockerize] Error 1
83221b80b135:~/go/dockerize$ go version
go version go1.10.1 linux/amd64
83221b80b135:~/go/dockerize$```
