### ISSUE TITLE
Force flag is not working?

### ISSUE THREAD

**Issue by daniele-athome** [jwilder/dockerize#90]
Using v0.5.0:

```
./dockerize -force -template test.tmpl:test [...]
```

The first line states:

```
flag provided but not defined: -force
```

And then it will exit with failure.

**Comment by jwilder** [comment]
It's `-no-overwrite`.  The default behavior is to overwrite the destination file.  `-no-overwrite` will cause the file to not be overwritten if it already exists.

**Comment by daniele-athome** [comment]
Sorry, I was misled by the README (didn't look at the inline help). Will you fix the README?

**Comment by jwilder** [comment]
Fixed.  Thanks.
