### ISSUE TITLE
Logs not displayed at first start if created by child process

### ISSUE THREAD

**Issue by daniele-athome** [jwilder/dockerize#91]
My container main process creates a log file during its execution. However, on first start, the file doesn't exist, so dockerize doesn't pick it up. A restart fixes the issue, but I would like dockerize to notice the file being created after the child process has started - possibly without using poll, inotify would be ideal.

Touching the log file before executing dockerize is not an option since the child process will not use it (it will create a log file with a different name).

**Comment by jwilder** [comment]
What version of dockerize are you using?  I'm not able to repro this with the latest.

**Comment by daniele-athome** [comment]
Using v0.5.0. Just tried with a simple bash script to reproduce this test case:

```
#!/bin/bash

sleep 3
echo "hello" >log
sleep 0.5
echo "world" >>log
sleep 1
echo "!" >>log
```

And then run it (even outside of docker) like this:

```
./dockerize -stdout log ./test.sh
```

Output is not displayed at first start because the log file will be created after 3 seconds, similar to my application (which creates the file moments after start, nevertheless it's not picked up by dockerize).

I don't know if this is expected behaviour by dockerize, I believe you could either:

* wait for the file to appear somehow (maybe inotify gives you that feature? I don't really know)
* add a command line argument to tell dockerize how much time to wait before attaching to the log file
* exit with error because the file doesn't exist prior to executing the child command

Using -poll works, but it has the side effect that in the above test script the last line is not printed out (I know it's a minor drawback, I'm pointing it out anyway).

What do you think?

**Comment by daniele-athome** [comment]
In the meantime... I discovered that actually touching the log file before start would work for the application I'm launching, so it could be my workaround... nevertheless, I'm interested to see your thoughts about this.

**Comment by jwilder** [comment]
If you can build from master, I pushed up a change to use an updated `hpcloud/tail` library that might fix this.

**Comment by daniele-athome** [comment]
I'm kind of new to go... I've installed go 1.8 and glock, cloned the repository from within ~/go/src and ran:

```
~/go/bin/glock sync $PWD
```

Output was:

```
github.com/elgs/gosplitargs                        a491c5eeb3c8 [get checkout e9cf3de21e14]
github.com/hpcloud/tail                            faf842bde7ed [get OK]
github.com/jwilder/gojq                            c550732d4a52 [get checkout 81fa9a608a13]
golang.org/x/net                                   ddf80d097059 [get checkout 749a502dd1ea]
```

And then I ran:

```
make
```

Which completed successfully and produced ~/go/bin/dockerize.

Weirdly, the result of the first execution was:

```
$ ./dockerize -stdout log ./test.sh
hello
2017/06/15 23:18:29 Command finished successfully.
```

Further executions work fine.

Did I do everything right?

**Comment by jwilder** [comment]
Going to assume this is fixed since I cannot reproduce as well.
