### ISSUE TITLE
Lookup ENV var from string?

### ISSUE THREAD

**Issue by ghostsquad** [jwilder/dockerize#99]
Is it possible to look up an env var using a string? Example:

```
{{ .Env["FOO"] }}
```
Instead of
```
{{ .Env.FOO
```

Extra to this, is it possible to define an array of strings and loop through them?

**Comment by jwilder** [comment]
I think you can do 

```
{{ index .Env "FOO" }}
```

The template docs are the standard go [text/template](https://golang.org/pkg/text/template/).  There is a `range` keyword for iteration as well.
